name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo Hi
    #   run: docker build . --file Dockerfile --tag custom-image:$(date +%s)
    # container:
    #   image: custom-image:$(date +%s)
    #   steps:
    #   - name: Build hello world
    #     run: cmake -S. -Bbuild . && cmake --build .
