name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: brunogriep/grpc-cpp:develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: check protoc
        run: |
          apt-get install -y protobuf-compiler
      - name: Running cmake config and building the project
        run: |
          ls -la
          cmake -S. -Bbuild . -DCMAKE_PREFIX_PATH=/usr/local
          cmake --build build
      - name: Run unit tests
        run: 
          ./build/test/example_test